name: Run CI

on: 
  # Only the default branch is supported.
  branch_protection_rule:
  schedule:
    - cron: '5 * * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tox:
    name: Run Tox
    steps:
    - uses: actions/checkout@v2
    - name: Run all envs
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py37, py38, py39, py310, py311, black, isort, flake8, mypy]
    runs-on: ubuntu-latest
